---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nutshell
  namespace: nutshell
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/hostname: acchiao.com
    external-dns.alpha.kubernetes.io/ttl: 5m
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
    service.beta.kubernetes.io/do-loadbalancer-name: raccoon
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - acchiao.com
    secretName: nutshell-tls
  rules:
  - host: acchiao.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nutshell
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nutshell
  namespace: nutshell
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nutshell
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutshell
  namespace: nutshell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nutshell
  template:
    metadata:
      labels:
        app: nutshell
    spec:
      containers:
      - name: nutshell
        image: ghcr.io/acchiao/nutshell:v0.0.3
        ports:
        - containerPort: 80
