---
name: Release

on:
  push:
    tags: [ "v*.*.*" ]
  workflow_dispatch:

env:
  PROJECT: raccoon-www

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    env:
      GIN_MODE: release
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            ghcr.io/${{ github.actor }}/${{ env.PROJECT }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{raw}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
            type=sha,prefix=,suffix=,format=long
            type=sha,prefix=,suffix=,format=short
      - uses: docker/build-push-action@v2
        id: build
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.actor }}/${{ env.PROJECT }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.actor }}/${{ env.PROJECT }}:buildcache,mode=max
      - run: echo ${{ steps.build.outputs.digest }}
